---
- name: Apache server installed
  hosts: web

  tasks:
    - name: latest Apache version installed
      ansible.builtin.yum:
        name: httpd
        state: latest

    - name: latest firewalld version installed
      ansible.builtin.yum:
        name: firewalld
        state: latest

    - name: firewalld enabled and running
      ansible.builtin.service:
        name: firewalld
        enabled: true
        state: started

    - name: firewalld permits http service
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true

    - name: Apache enabled and running
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started
