---
- name: Restore SELinux Policy
  hosts: web
  gather_facts: false


  tasks:
    
    - name: restore SELinux to enforcing
      ansible.posix.selinux:
        policy: targeted
        state: enforcing
      

